### ISSUE TITLE
Make object paths stable across restarts (of dleyna-server and of the DMS)

### ISSUE THREAD

**Issue by em-** [01org/dleyna-server#119]
Currently DMSes are identified by sequential integers which depends on the order they're first seen by dleyna-server (eg. `/com/intel/dLeynaServer/server/2`).

This means that it will be impossible to keep persistent references to objects across DMS or dleyna-server restarts, as media items will have paths like `/com/intel/dLeynaServer/server/2/3034306130393764373063393261313636623936616133623835663332306334`.

To address this we could use the udn as stable server identifier, eg. `/com/intel/dLeynaServer/server/uuid/6da19ece-c964-4094-a2bd-84249e8c7da6`.

To also allow for more compact and closer to the original representation of the media item identifiers something like [`tp_escape_as_identifier()`](http://cgit.freedesktop.org/telepathy/telepathy-glib/tree/telepathy-glib/util.c#n706) could be employed, escaping only invalid characters instead of always doubling the required string length as done by [`prv_id_to_object_name()`](https://github.com/01org/dleyna-server/blob/master/libdleyna/server/path.c#L125).

**Comment by tkem** [comment]
What's the status of this issue? I have a use case where I'd like to store paths to media items in playlists in the client, so these should not change with client restarts.
Also having media servers change their paths when they are restarted is quite annoying.

**Comment by rsbells** [comment]
We understand needs to be done. We have some code that will address this issue in dleyna-renderer. We need to implement it in dleyna-server and test both dleyna-renderer. I will let you know when it has been merged in.

**Comment by tkem** [comment]
Great news! Thanks for sharing this awesome project and continuing to support it!

**Comment by rsbells** [comment]
I created dleyna_core_prv_convert_udn_to_path API in the dleyna-core so this can be used for both dleyna-renderer and dleyna server.  You need the latest code for dleyna-core, dleyna-server, and dleyna-renderer.
