### ISSUE TITLE
Dereference of undefined pointer value

### ISSUE THREAD

**Issue by phako** [01org/dleyna-server#154]
```
device.c    prv_retrieve_child_count_for_list   1883    
```

![screenshot from 2016-09-25 22-47-00](https://cloud.githubusercontent.com/assets/55554/18818143/0389d04c-8372-11e6-8845-66e29cbb4a71.png)

**Comment by rsbells** [comment]
Phako - Please confirm...

**Comment by phako** [comment]
:+1:
